server:
  port: 8086

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: credit-score-service
          uri: http://localhost:8084
          predicates:
            - Path=/scores/**
        - id: data-collection-service
          uri: http://localhost:8083
          predicates:
            - Path=/data/**
        - id: report-service
          uri: http://localhost:8082
          predicates:
            - Path=/reports/**
